name: Pruebas TAQI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov sqlalchemy
      - name: Ejecutar pruebas
        run: |
          cd taqi-app-finanzas
          pip install sqlalchemy
          pytest test_app.py -v
